<a href="https://colab.research.google.com/github/andersonhsu90/homework/blob/master/Linear_algebra_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [0]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [0]:
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

In [0]:
print(5 * A)
print(A ** 3)
print(A + B)
print(A - B)
print(A * B)

[[25 30 10]
 [20 35 95]
 [ 0 15 60]]
[[ 557 1284 3356]
 [ 760 2305 6994]
 [ 288 1074 3519]]
[[19  4 14]
 [ 8 11 24]
 [ 5  8 13]]
[[ -9   8 -10]
 [  0   3  14]
 [ -5  -2  11]]
[[104  24  92]
 [179 115 102]
 [ 72  72  27]]


In [0]:
c=np.matrix([[1,-1],[2,1]])
print(c ** 2-2*c+3)

[[0 3]
 [3 0]]
